build:
  image: docker:19.03.11
  stage: build
  services:
    - docker:19.03.11-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cd docker
    - docker build -t $CI_REGISTRY/tomomano/intro-aws:latest .
    - docker push $CI_REGISTRY/tomomano/intro-aws:latest
  only:
    - master

pages:
  image: ruby:2.6
  stage: deploy
  script:
    - cd book
    - gem install bundler
    - bundle install
    - ./generate.sh main.adoc
    - cp -r dist ../public
  artifacts:
    paths:
      - public
  only:
    - master
