image: ruby:2.6

pages:
  stage: deploy
  script:
    - cd book
    - gem install bundler
    - bundle install
    - ./generate.sh main.adoc
    - cp -r dist ../public
  artifacts:
    paths:
      - public
  only:
    - master
