# build docker image with Python, node.js, AWS CLI, AWS CDK etc. 
docker:
  image: docker:19.03.11
  stage: build
  services:
    - docker:19.03.11-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/tomomano/intro-aws:latest docker/
    - docker push $CI_REGISTRY/tomomano/intro-aws:latest
  only:
    - master

# Build docker image for handson-03
docker-handson-03:
  image: docker:19.03.11
  stage: build
  services:
    - docker:19.03.11-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/tomomano/intro-aws/handson03:latest handson/03-qa-bot/docker/
    - docker push $CI_REGISTRY/tomomano/intro-aws/handson03:latest
  only:
    - master

# deploy HTML and PDF
pages:
  image: ruby:2.6
  stage: deploy
  script:
    - cd book
    - gem install bundler
    - bundle install
    - ./generate.sh main.adoc
    - cp -r dist ../public
  artifacts:
    paths:
      - public
  only:
    - master
